### ISSUE TITLE
An illegalStateException occurs when REST method's argument contains two classes with same name

### ISSUE THREAD

**Issue by yizhangy** [teamcarma/swagger-jaxrs-doclet#109]
I have a REST resource take a DTO class as argument. This dto class has two properties, which have same class name but in different package. For example:
```
@POST
@Path("/{id}")
@Produces({ MediaType.APPLICATION_JSON })
public UserDto doWorkflowAction(@Context final UserDto userDto,@PathParam("id") final String id)

```
UserDto class contains two properties, which have same class name but in different package
```
public class UserDto {
       private com.mypackage.user.Identifier userIdentifier;
       private com.mypackage.address.Identifier addressIdentifier;

```

When I use swagger-jaxrs-doclet to generate java doc. I get exception:
```
java.lang.IllegalStateException: dupe models, method : {sorroy, I cannot post my model here. but I saw two duplicated model ids}
at com.carma.swagger.doclet.parser.CrossClassApiParser.addApiModels(CrossClassApiParser.java:244)
build	15-Sep-2015 21:19:28	  [javadoc] 	at com.carma.swagger.doclet.parser.CrossClassApiParser.parse(CrossClassApiParser.java:190)
build	15-Sep-2015 21:19:28	  [javadoc] 	at com.carma.swagger.doclet.parser.JaxRsAnnotationParser.run(JaxRsAnnotationParser.java:160)
build	15-Sep-2015 21:19:28	  [javadoc] 	at com.carma.swagger.doclet.ServiceDoclet.start(ServiceDoclet.java:33)
build	15-Sep-2015 21:19:28	  [javadoc] 	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
build	15-Sep-2015 21:19:28	  [javadoc] 	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
build	15-Sep-2015 21:19:28	  [javadoc] 	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
build	15-Sep-2015 21:19:28	  [javadoc] 	at java.lang.reflect.Method.invoke(Method.java:497)
build	15-Sep-2015 21:19:28	  [javadoc] 	at com.sun.tools.javadoc.DocletInvoker.invoke(DocletInvoker.java:310)
build	15-Sep-2015 21:19:28	  [javadoc] 	at com.sun.tools.javadoc.DocletInvoker.start(DocletInvoker.java:189)
build	15-Sep-2015 21:19:28	  [javadoc] 	at com.sun.tools.javadoc.Start.parseAndExecute(Start.java:366)
build	15-Sep-2015 21:19:28	  [javadoc] 	at com.sun.tools.javadoc.Start.begin(Start.java:219)
build	15-Sep-2015 21:19:28	  [javadoc] 	at com.sun.tools.javadoc.Start.begin(Start.java:205)
build	15-Sep-2015 21:19:28	  [javadoc] 	at com.sun.tools.javadoc.Main.execute(Main.java:64)
build	15-Sep-2015 21:19:28	  [javadoc] 	at com.sun.tools.javadoc.Main.main(Main.java:54)
build	15-Sep-2015 21:19:28	  [javadoc] Caused by: java.lang.IllegalArgumentException: duplicate key: Identifier
build	15-Sep-2015 21:19:28	  [javadoc] 	at com.google.common.base.Preconditions.checkArgument(Preconditions.java:119)
build	15-Sep-2015 21:19:28	  [javadoc] 	at com.google.common.collect.RegularImmutableMap.<init>(RegularImmutableMap.java:67)
build	15-Sep-2015 21:19:28	  [javadoc] 	at com.google.common.collect.ImmutableMap$Builder.fromEntryList(ImmutableMap.java:249)
build	15-Sep-2015 21:19:28	  [javadoc] 	at com.google.common.collect.ImmutableMap$Builder.build(ImmutableMap.java:235)
build	15-Sep-2015 21:19:28	  [javadoc] 	at com.google.common.collect.Maps.uniqueIndex(Maps.java:1168)
build	15-Sep-2015 21:19:28	  [javadoc] 	at com.google.common.collect.Maps.uniqueIndex(Maps.java:1142)
build	15-Sep-2015 21:19:28	  [javadoc] 	at com.carma.swagger.doclet.parser.CrossClassApiParser.addApiModels(CrossClassApiParser.java:237)
```
The method's model id should use qualified class name.

**Comment by conorroche** [comment]
@yizhangy I have added a doclet option -useFullModelIds that should solve your problem, i did not enable it by default as for most people the shorter model id will look better, can you test and let me know if it works ok for you?

**Comment by yizhangy** [comment]
@conorroche Thanks. I will try it.

**Comment by yizhangy** [comment]
@conorroche The version I used is swagger-doclet-1.0.6-SNAPSHOT.jar and failed with '-useFullModelIds' flag. Can you please point to me which version of jar for working with this flag? thank you

**Comment by conorroche** [comment]
i have not merged this fix onto the java 7 branch, its only on the java 8 master so the version that its on is 1.1.2-SNAPSHOT

**Comment by conorroche** [comment]
@yizhangy can you confirm if this is ok for you now?

**Comment by yizhangy** [comment]
@conorroche at this moment I am not working on our build script. I did not verify it. I will let you know when our build pass.

**Comment by yizhangy** [comment]
@conorroche  have you merged this fix into the java 7 branch.
