### ISSUE TITLE
Stackoverflow from bidirectional sub resources

### ISSUE THREAD

**Issue by TuomasKiviaho** [teamcarma/swagger-jaxrs-doclet#52]
CrossClassApiParser never finishes when sub resources generate net structure instead of the usual tree structure.

A fix could be to check whether or not subresource is already being parsed before creating subResourceParser

```
[ERROR] javadoc: error - In doclet class com.carma.swagger.doclet.ServiceDoclet,  method start has thrown an exception java.lang.reflect.InvocationTargetException
[ERROR] java.lang.StackOverflowError
[ERROR] at java.io.UnixFileSystem.getBooleanAttributes0(Native Method)
[ERROR] at java.io.UnixFileSystem.getBooleanAttributes(UnixFileSystem.java:242)
[ERROR] at java.io.File.exists(File.java:813)
[ERROR] at sun.misc.URLClassPath$FileLoader.getResource(URLClassPath.java:1080)
[ERROR] at sun.misc.URLClassPath.getResource(URLClassPath.java:199)
[ERROR] at java.net.URLClassLoader$1.run(URLClassLoader.java:358)
[ERROR] at java.net.URLClassLoader$1.run(URLClassLoader.java:355)
[ERROR] at java.security.AccessController.doPrivileged(Native Method)
[ERROR] at java.net.URLClassLoader.findClass(URLClassLoader.java:354)
[ERROR] at java.lang.ClassLoader.loadClass(ClassLoader.java:425)
[ERROR] at java.lang.ClassLoader.loadClass(ClassLoader.java:358)
[ERROR] at java.lang.Class.forName0(Native Method)
[ERROR] at java.lang.Class.forName(Class.java:191)
[ERROR] at com.carma.swagger.doclet.parser.ParserHelper.isCollection(ParserHelper.java:454)
[ERROR] at com.carma.swagger.doclet.parser.ParserHelper.typeOf(ParserHelper.java:336)
[ERROR] at com.carma.swagger.doclet.parser.ParserHelper.typeOf(ParserHelper.java:385)
[ERROR] at com.carma.swagger.doclet.translator.NameBasedTranslator.typeName(NameBasedTranslator.java:74)
[ERROR] at com.carma.swagger.doclet.translator.NameBasedTranslator.parameterTypeName(NameBasedTranslator.java:48)
[ERROR] at com.carma.swagger.doclet.translator.FirstNotNullTranslator$2.apply(FirstNotNullTranslator.java:62)
[ERROR] at com.carma.swagger.doclet.translator.FirstNotNullTranslator$2.apply(FirstNotNullTranslator.java:59)
[ERROR] at com.carma.swagger.doclet.translator.FirstNotNullTranslator.firstNotNullOf(FirstNotNullTranslator.java:110)
[ERROR] at com.carma.swagger.doclet.translator.FirstNotNullTranslator.parameterTypeName(FirstNotNullTranslator.java:59)
[ERROR] at com.carma.swagger.doclet.parser.ApiMethodParser.generateParameters(ApiMethodParser.java:567)
[ERROR] at com.carma.swagger.doclet.parser.ApiMethodParser.parse(ApiMethodParser.java:175)
[ERROR] at com.carma.swagger.doclet.parser.CrossClassApiParser.parse(CrossClassApiParser.java:139)
[ERROR] at com.carma.swagger.doclet.parser.CrossClassApiParser.parse(CrossClassApiParser.java:157)
[ERROR] at com.carma.swagger.doclet.parser.CrossClassApiParser.parse(CrossClassApiParser.java:157)
[ERROR] at com.carma.swagger.doclet.parser.CrossClassApiParser.parse(CrossClassApiParser.java:157)
[ERROR] at com.carma.swagger.doclet.parser.CrossClassApiParser.parse(CrossClassApiParser.java:157)
[ERROR] at com.carma.swagger.doclet.parser.CrossClassApiParser.parse(CrossClassApiParser.java:157)
[ERROR] at com.carma.swagger.doclet.parser.CrossClassApiParser.parse(CrossClassApiParser.java:157)
[ERROR] at com.carma.swagger.doclet.parser.CrossClassApiParser.parse(CrossClassApiParser.java:157)
...
```

**Comment by conorroche** [comment]
@TuomasKiviaho i already use a different class set to prevent against this but it obviously doesn't work in your case, could you give me code for sample resources that can reproduce this?

**Comment by conorroche** [comment]
@TuomasKiviaho i have tried reproducing using bidirectional sub resources like these but have had no luck:

@Path("/bidir")
public class MainRes {

	@Path("/a")
	public ResA getA() {
		return null;
	}

}

public class ResA {

	@Path("/get")
	@GET
	public String get() {
		return null;
	}

	@Path("/b")
	public ResB getB() {
		return null;
	}

}

public class ResB {

	@Path("/get")
	@GET
	public String get() {
		return null;
	}

	@Path("/a")
	public ResA getA() {
		return null;
	}

}

could you provide me with more details of your use case

**Comment by TuomasKiviaho** [comment]
I got the debugger up and running but ```CrossClassApiParser``` now seems only to nag about 
```
System.err.println("Failed to lookup sub resource class doc: " + method.returnType() + " looked up type is: " + lookUpClassDoc(method.returnType()));
```
every time it sees the sub resource again which is quite a lot when there are lot of cyclic references. I wonder if I might have worked around this problem already.

**Comment by conorroche** [comment]
What return type and looked up type does it actually output?

**Comment by TuomasKiviaho** [comment]
The latter is null because the class was omitted in order to prevent infinite loop. There's already hundred lines and I'm afraid this will only multiply each time I introduce a new cyclic reference to my net of sub resources. Good thing is that it doesn't loop indefinitely anymore and I get a decent output.

PS. One thing that might be helpful is to output the error using ``com.sun.java.doc.DocErrorReporter`` interface that ``RootDoc`` provides. This way maven might be able to suppress these lines that now go to ``System.err``
```
Constructing Javadoc information...
Failed to lookup sub resource class doc: com.example.Foobar1 looked up type is: null
Failed to lookup sub resource class doc: com.example.Foobar1 looked up type is: null
Failed to lookup sub resource class doc: com.example.Foobar1 looked up type is: null
Failed to lookup sub resource class doc: com.example.Foobar1 looked up type is: null
Failed to lookup sub resource class doc: com.example.Foobar1 looked up type is: null
Failed to lookup sub resource class doc: com.example.Foobar2 looked up type is: null
Failed to lookup sub resource class doc: com.example.Foobar1 looked up type is: null
Failed to lookup sub resource class doc: com.example.Foobar1 looked up type is: null
Failed to lookup sub resource class doc: com.example.Foobar1 looked up type is: null
Failed to lookup sub resource class doc: com.example.Foobar1 looked up type is: null
Failed to lookup sub resource class doc: com.example.Foobar1 looked up type is: null
Failed to lookup sub resource class doc: com.example.Foobar1 looked up type is: null
Failed to lookup sub resource class doc: com.example.Foobar1 looked up type is: null
Failed to lookup sub resource class doc: com.example.Foobar1 looked up type is: null
Failed to lookup sub resource class doc: com.example.Foobar1 looked up type is: null
Failed to lookup sub resource class doc: com.example.Foobar2 looked up type is: null
Failed to lookup sub resource class doc: com.example.Foobar1 looked up type is: null
Failed to lookup sub resource class doc: com.example.Foobar2 looked up type is: null
Failed to lookup sub resource class doc: com.example.Foobar1 looked up type is: null
Failed to lookup sub resource class doc: com.example.Foobar1 looked up type is: null
Failed to lookup sub resource class doc: com.example.Foobar1 looked up type is: null
Failed to lookup sub resource class doc: com.example.Foobar1 looked up type is: null
Failed to lookup sub resource class doc: com.example.Foobar1 looked up type is: null
Failed to lookup sub resource class doc: com.example.Foobar1 looked up type is: null
Failed to lookup sub resource class doc: com.example.Foobar2 looked up type is: null
Failed to lookup sub resource class doc: com.example.Foobar1 looked up type is: null
Failed to lookup sub resource class doc: com.example.Foobar1 looked up type is: null
Failed to lookup sub resource class doc: com.example.Foobar1 looked up type is: null
Failed to lookup sub resource class doc: com.example.Foobar1 looked up type is: null
Failed to lookup sub resource class doc: com.example.Foobar1 looked up type is: null
Failed to lookup sub resource class doc: com.example.Foobar1 looked up type is: null
Failed to lookup sub resource class doc: com.example.Foobar1 looked up type is: null
Failed to lookup sub resource class doc: com.example.Foobar1 looked up type is: null
Failed to lookup sub resource class doc: com.example.Foobar1 looked up type is: null
Failed to lookup sub resource class doc: com.example.Foobar2 looked up type is: null
Failed to lookup sub resource class doc: com.example.Foobar1 looked up type is: null
Failed to lookup sub resource class doc: com.example.Foobar2 looked up type is: null
Failed to lookup sub resource class doc: com.example.Foobar1 looked up type is: null
Failed to lookup sub resource class doc: com.example.Foobar1 looked up type is: null
Failed to lookup sub resource class doc: com.example.Foobar1 looked up type is: null
Failed to lookup sub resource class doc: com.example.Foobar1 looked up type is: null
Failed to lookup sub resource class doc: com.example.Foobar1 looked up type is: null
Failed to lookup sub resource class doc: com.example.Foobar1 looked up type is: null
Failed to lookup sub resource class doc: com.example.Foobar2 looked up type is: null
Failed to lookup sub resource class doc: com.example.Foobar1 looked up type is: null
Failed to lookup sub resource class doc: com.example.Foobar1 looked up type is: null
Failed to lookup sub resource class doc: com.example.Foobar1 looked up type is: null
Failed to lookup sub resource class doc: com.example.Foobar1 looked up type is: null
Failed to lookup sub resource class doc: com.example.Foobar1 looked up type is: null
Failed to lookup sub resource class doc: com.example.Foobar1 looked up type is: null
Failed to lookup sub resource class doc: com.example.Foobar1 looked up type is: null
Failed to lookup sub resource class doc: com.example.Foobar1 looked up type is: null
Failed to lookup sub resource class doc: com.example.Foobar1 looked up type is: null
Failed to lookup sub resource class doc: com.example.Foobar2 looked up type is: null
Failed to lookup sub resource class doc: com.example.Foobar1 looked up type is: null
Failed to lookup sub resource class doc: com.example.Foobar2 looked up type is: null
Failed to lookup sub resource class doc: com.example.Foobar1 looked up type is: null
Failed to lookup sub resource class doc: com.example.Foobar3 looked up type is: null
Failed to lookup sub resource class doc: com.example.Foobar1 looked up type is: null
Failed to lookup sub resource class doc: com.example.Foobar1 looked up type is: null
Failed to lookup sub resource class doc: com.example.Foobar1 looked up type is: null
Failed to lookup sub resource class doc: com.example.Foobar1 looked up type is: null
Failed to lookup sub resource class doc: com.example.Foobar1 looked up type is: null
Failed to lookup sub resource class doc: com.example.Foobar2 looked up type is: null
Failed to lookup sub resource class doc: com.example.Foobar1 looked up type is: null
Failed to lookup sub resource class doc: com.example.Foobar1 looked up type is: null
Failed to lookup sub resource class doc: com.example.Foobar1 looked up type is: null
Failed to lookup sub resource class doc: com.example.Foobar1 looked up type is: null
Failed to lookup sub resource class doc: com.example.Foobar1 looked up type is: null
Failed to lookup sub resource class doc: com.example.Foobar1 looked up type is: null
Failed to lookup sub resource class doc: com.example.Foobar1 looked up type is: null
Failed to lookup sub resource class doc: com.example.Foobar1 looked up type is: null
Failed to lookup sub resource class doc: com.example.Foobar2 looked up type is: null
Failed to lookup sub resource class doc: com.example.Foobar2 looked up type is: null
Failed to lookup sub resource class doc: com.example.Foobar2 looked up type is: null
Failed to lookup sub resource class doc: com.example.Foobar1 looked up type is: null
Failed to lookup sub resource class doc: com.example.Foobar1 looked up type is: null
Failed to lookup sub resource class doc: com.example.Foobar1 looked up type is: null
Failed to lookup sub resource class doc: com.example.Foobar1 looked up type is: null
Failed to lookup sub resource class doc: com.example.Foobar1 looked up type is: null
Failed to lookup sub resource class doc: com.example.Foobar2 looked up type is: null
Failed to lookup sub resource class doc: com.example.Foobar1 looked up type is: null
Failed to lookup sub resource class doc: com.example.Foobar1 looked up type is: null
Failed to lookup sub resource class doc: com.example.Foobar1 looked up type is: null
Failed to lookup sub resource class doc: com.example.Foobar1 looked up type is: null
Failed to lookup sub resource class doc: com.example.Foobar1 looked up type is: null
Failed to lookup sub resource class doc: com.example.Foobar1 looked up type is: null
Failed to lookup sub resource class doc: com.example.Foobar1 looked up type is: null
Failed to lookup sub resource class doc: com.example.Foobar1 looked up type is: null
Failed to lookup sub resource class doc: com.example.Foobar2 looked up type is: null
Failed to lookup sub resource class doc: com.example.Foobar2 looked up type is: null
Failed to lookup sub resource class doc: com.example.Foobar1 looked up type is: null
Failed to lookup sub resource class doc: com.example.Foobar4 looked up type is: null
Failed to lookup sub resource class doc: com.example.Foobar5 looked up type is: null
Failed to lookup sub resource class doc: com.example.Foobar1 looked up type is: null
Failed to lookup sub resource class doc: com.example.Foobar2 looked up type is: null
Failed to lookup sub resource class doc: com.example.Foobar1 looked up type is: null
Failed to lookup sub resource class doc: com.example.Foobar4 looked up type is: null
Failed to lookup sub resource class doc: com.example.Foobar5 looked up type is: null
Failed to lookup sub resource class doc: com.example.Foobar1 looked up type is: null
Failed to lookup sub resource class doc: com.example.Foobar4 looked up type is: null
Failed to lookup sub resource class doc: com.example.Foobar5 looked up type is: null
Failed to lookup sub resource class doc: com.example.Foobar1 looked up type is: null
Failed to lookup sub resource class doc: com.example.Foobar2 looked up type is: null
Failed to lookup sub resource class doc: com.example.Foobar1 looked up type is: null
Failed to lookup sub resource class doc: com.example.Foobar2 looked up type is: null
Failed to lookup sub resource class doc: com.example.Foobar1 looked up type is: null
Failed to lookup sub resource class doc: com.example.Foobar1 looked up type is: null
Failed to lookup sub resource class doc: com.example.Foobar4 looked up type is: null
Failed to lookup sub resource class doc: com.example.Foobar1 looked up type is: null
Failed to lookup sub resource class doc: com.example.Foobar1 looked up type is: null
Failed to lookup sub resource class doc: com.example.Foobar2 looked up type is: null
Failed to lookup sub resource class doc: com.example.Foobar1 looked up type is: null
Failed to lookup sub resource class doc: com.example.Foobar4 looked up type is: null
Failed to lookup sub resource class doc: com.example.Foobar1 looked up type is: null
Failed to lookup sub resource class doc: com.example.Foobar1 looked up type is: null
Failed to lookup sub resource class doc: com.example.Foobar4 looked up type is: null
Failed to lookup sub resource class doc: com.example.Foobar1 looked up type is: null
Failed to lookup sub resource class doc: com.example.Foobar1 looked up type is: null
Failed to lookup sub resource class doc: com.example.Foobar2 looked up type is: null
Failed to lookup sub resource class doc: com.example.Foobar1 looked up type is: null
Failed to lookup sub resource class doc: com.example.Foobar2 looked up type is: null
Failed to lookup sub resource class doc: com.example.Foobar1 looked up type is: null
Failed to lookup sub resource class doc: com.example.Foobar1 looked up type is: null
Failed to lookup sub resource class doc: com.example.Foobar1 looked up type is: null
Failed to lookup sub resource class doc: com.example.Foobar1 looked up type is: null
Failed to lookup sub resource class doc: com.example.Foobar1 looked up type is: null
Failed to lookup sub resource class doc: com.example.Foobar1 looked up type is: null
Failed to lookup sub resource class doc: com.example.Foobar2 looked up type is: null
Failed to lookup sub resource class doc: com.example.Foobar1 looked up type is: null
Failed to lookup sub resource class doc: com.example.Foobar1 looked up type is: null
Failed to lookup sub resource class doc: com.example.Foobar1 looked up type is: null
Failed to lookup sub resource class doc: com.example.Foobar1 looked up type is: null
Failed to lookup sub resource class doc: com.example.Foobar1 looked up type is: null
Failed to lookup sub resource class doc: com.example.Foobar1 looked up type is: null
Failed to lookup sub resource class doc: com.example.Foobar1 looked up type is: null
Failed to lookup sub resource class doc: com.example.Foobar1 looked up type is: null
Failed to lookup sub resource class doc: com.example.Foobar1 looked up type is: null
Failed to lookup sub resource class doc: com.example.Foobar2 looked up type is: null
Failed to lookup sub resource class doc: com.example.Foobar1 looked up type is: null
Failed to lookup sub resource class doc: com.example.Foobar2 looked up type is: null
Failed to lookup sub resource class doc: com.example.Foobar1 looked up type is: null
Using default swagger-ui.zip file from SwaggerDoclet jar file
```

**Comment by conorroche** [comment]
ive removed the error messages in the latest snapshot

**Comment by conorroche** [comment]
@TuomasKiviaho if you could post the src of com.example.Foobar1, com.example.Foobar2, com.example.Foobar4 and the parent resource etc that would really help me reproduce and resolve it properly

**Comment by TuomasKiviaho** [comment]
Thanks, They come from quite a big non-public ORM model so I have would have to narrow down (and obfuscate)  them first, but so far what I've discovered is that..

- Interfaces are not processed (see resteasy client side proxy support)
- Nested subresources still end up to the root level for me.

I'll make a pull request out of these first so that I can reduce the produced JSON to mere fraction what it is now and maybe then I can make more sense to this matter as well, but I guess this might just be a side effect.

**Comment by TuomasKiviaho** [comment]
I found out that /directory/directory/directory.... mapping is not possible with 1.2 spec because it (https://github.com/swagger-api/swagger-spec/blob/master/versions/1.2.md#522-api-object) doesn't have $ref as does 2.0 (https://github.com/swagger-api/swagger-spec/blob/master/versions/2.0.md#pathItemObject)

**Comment by TuomasKiviaho** [comment]
Here's the pull request #59 I promised

**Comment by conorroche** [comment]
closing as according to the pull request this is no longer an issue and I could never reproduce
