### ISSUE TITLE
@responseType doesn't support primitives

### ISSUE THREAD

**Issue by nkoterba** [teamcarma/swagger-jaxrs-doclet#76]
I have a method that returns a JAX-RS Response object, but in reality it's entity is a string:

```java
	/**
	 * @responseType string
	 * @responseMessage 200 Echo GET endpoint successfully reached
	 * @responseMessage 404 Not found; indicates REST services currently unavailable
	 * @return "echo" if successful request
	 */
	@GET
	@Produces(MediaType.TEXT_PLAIN)
	public Response get() {
		Log.info("{get}: context := {}", context);
		return Response.ok("echo").build();
	}
```

When I try to compile the documentation, I get this error:
```java
java.lang.IllegalStateException: Could not find the source for the custom response class: string. If it is not in the same project as the one you have added the doclet to, for example if it is in a dependent project then you should copy the source to the doclet calling project using the maven-dependency-plugin's unpack goal, and then add it to the source using the build-helper-maven-plugin's add-source goal.
	at com.carma.swagger.doclet.parser.ApiMethodParser.raiseCustomTypeNotFoundError(ApiMethodParser.java:833)
	at com.carma.swagger.doclet.parser.ApiMethodParser.readCustomReturnType(ApiMethodParser.java:783)
	at com.carma.swagger.doclet.parser.ApiMethodParser.parse(ApiMethodParser.java:152)
	at com.carma.swagger.doclet.parser.CrossClassApiParser.parse(CrossClassApiParser.java:142)
	at com.carma.swagger.doclet.parser.JaxRsAnnotationParser.run(JaxRsAnnotationParser.java:126)
	at com.carma.swagger.doclet.apidocs.PrimitivesTest.testStart(PrimitivesTest.java:37)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:57)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at org.junit.runners.model.FrameworkMethod$1.runReflectiveCall(FrameworkMethod.java:47)
	at org.junit.internal.runners.model.ReflectiveCallable.run(ReflectiveCallable.java:12)
	at org.junit.runners.model.FrameworkMethod.invokeExplosively(FrameworkMethod.java:44)
	at org.junit.internal.runners.statements.InvokeMethod.evaluate(InvokeMethod.java:17)
	at org.junit.internal.runners.statements.RunBefores.evaluate(RunBefores.java:26)
	at org.junit.runners.ParentRunner.runLeaf(ParentRunner.java:271)
	at org.junit.runners.BlockJUnit4ClassRunner.runChild(BlockJUnit4ClassRunner.java:70)
	at org.junit.runners.BlockJUnit4ClassRunner.runChild(BlockJUnit4ClassRunner.java:50)
	at org.junit.runners.ParentRunner$3.run(ParentRunner.java:238)
	at org.junit.runners.ParentRunner$1.schedule(ParentRunner.java:63)
	at org.junit.runners.ParentRunner.runChildren(ParentRunner.java:236)
	at org.junit.runners.ParentRunner.access$000(ParentRunner.java:53)
	at org.junit.runners.ParentRunner$2.evaluate(ParentRunner.java:229)
	at org.junit.runners.ParentRunner.run(ParentRunner.java:309)
	at org.junit.runner.JUnitCore.run(JUnitCore.java:160)
	at com.intellij.rt.execution.junit.JUnitStarter.main(JUnitStarter.java:68)
```

Trying `java.lang.String` also throws the same error:
```java
java.lang.IllegalStateException: Could not find the source for the custom response class: java.lang.String. If it is not in the same project as the one you have added the doclet to, for example if it is in a dependent project then you should copy the source to the doclet calling project using the maven-dependency-plugin's unpack goal, and then add it to the source using the build-helper-maven-plugin's add-source goal.
	at com.carma.swagger.doclet.parser.ApiMethodParser.raiseCustomTypeNotFoundError(ApiMethodParser.java:833)
	at com.carma.swagger.doclet.parser.ApiMethodParser.readCustomReturnType(ApiMethodParser.java:783)
	at com.carma.swagger.doclet.parser.ApiMethodParser.parse(ApiMethodParser.java:152)
	at com.carma.swagger.doclet.parser.CrossClassApiParser.parse(CrossClassApiParser.java:142)
	at com.carma.swagger.doclet.parser.JaxRsAnnotationParser.run(JaxRsAnnotationParser.java:126)
	at com.carma.swagger.doclet.apidocs.PrimitivesTest.testStart(PrimitivesTest.java:37)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:57)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at org.junit.runners.model.FrameworkMethod$1.runReflectiveCall(FrameworkMethod.java:47)
	at org.junit.internal.runners.model.ReflectiveCallable.run(ReflectiveCallable.java:12)
	at org.junit.runners.model.FrameworkMethod.invokeExplosively(FrameworkMethod.java:44)
	at org.junit.internal.runners.statements.InvokeMethod.evaluate(InvokeMethod.java:17)
	at org.junit.internal.runners.statements.RunBefores.evaluate(RunBefores.java:26)
	at org.junit.runners.ParentRunner.runLeaf(ParentRunner.java:271)
	at org.junit.runners.BlockJUnit4ClassRunner.runChild(BlockJUnit4ClassRunner.java:70)
	at org.junit.runners.BlockJUnit4ClassRunner.runChild(BlockJUnit4ClassRunner.java:50)
	at org.junit.runners.ParentRunner$3.run(ParentRunner.java:238)
	at org.junit.runners.ParentRunner$1.schedule(ParentRunner.java:63)
	at org.junit.runners.ParentRunner.runChildren(ParentRunner.java:236)
	at org.junit.runners.ParentRunner.access$000(ParentRunner.java:53)
	at org.junit.runners.ParentRunner$2.evaluate(ParentRunner.java:229)
	at org.junit.runners.ParentRunner.run(ParentRunner.java:309)
	at org.junit.runner.JUnitCore.run(JUnitCore.java:160)
	at com.intellij.rt.execution.junit.JUnitStarter.main(JUnitStarter.java:68)
```

The issue is in the `ApiMethodParser.java` class.  Specifically, the ParserHelper.findModel checks a list of PRIMITIVE classes.  However, String is not added to this list:
```java
static final Map<String, String> PRIMITIVE_TO_CLASS = new HashMap<String, String>();
	static {
		PRIMITIVE_TO_CLASS.put("int", java.lang.Integer.class.getName());
		PRIMITIVE_TO_CLASS.put("boolean", java.lang.Boolean.class.getName());
		PRIMITIVE_TO_CLASS.put("float", java.lang.Float.class.getName());
		PRIMITIVE_TO_CLASS.put("double", java.lang.Double.class.getName());
		PRIMITIVE_TO_CLASS.put("char", java.lang.Character.class.getName());
		PRIMITIVE_TO_CLASS.put("long", java.lang.Long.class.getName());
		PRIMITIVE_TO_CLASS.put("byte", java.lang.Byte.class.getName());
	}
```

Furthermore, the `ParserHelper.findModel` class does not correctly handle primitive values because once it gets a Primitive's fully-qualified class name, it tries to check that against the model classes.  Unfortunately, Java primitives are not added to the model classes collection...perhaps they should be?

In the method below, even if I add string to the PRIMTIIVE_TO_CLASS Hashmap, e.g.:
```java
PRIMITIVE_TO_CLASS.put("string", java.lang.String.class.getName());
```

it will still fail because `java.lang.String` will never be found in the for loop below:
```java
/**
	 * This finds a model class by the given name
	 * @param classes The model classes
	 * @param qualifiedClassName The FQN of the class
	 * @return {@link ClassDoc} found among all classes processed by the doclet based on a given <code>qualifiedClassName</code>; <code>null</code> if not found
	 */
	public static ClassDoc findModel(Collection<ClassDoc> classes, String qualifiedClassName) {
		System.out.println("Finding model: " + qualifiedClassName);
		System.out.println("Classes: " + classes);
		if (classes != null && qualifiedClassName != null) {
			// map primitives to their class equiv
			if (PRIMITIVE_TO_CLASS.containsKey(qualifiedClassName)) {
				qualifiedClassName = PRIMITIVE_TO_CLASS.get(qualifiedClassName);
			}
			for (ClassDoc cls : classes) {
				if (qualifiedClassName.equals(cls.qualifiedName())) {
					return cls;
				}
			}
		}
		return null;
	}
```

I'm not sure how to handle this scenario.  I do believe that `@responseType` should support primitive types and not just model types since I might be returning a `String` but in reality my method returns a JAX-RS `Response`.

**Comment by nkoterba** [comment]
I think I've found the issue.  In `ApiMethodParser.java` the line that calls ParserHelper.findModel is passing in `this.classes` instead of `this.allclasses`.

https://github.com/teamcarma/swagger-jaxrs-doclet/blob/master/swagger-doclet/src/main/java/com/carma/swagger/doclet/parser/ApiMethodParser.java#L818

could be changed to `this.allClasses`.  This would ensure primitives are also available for `@responseType` annotations.

Switching that code allowed me to successfully use primitives in `@responseType`.

**Comment by conorroche** [comment]
Ive now applied this fix to the master
